// AUTO-GENERATED by docs-site/scripts/build-chat-context.mjs
// Do not edit by hand. Re-run `pnpm build:chat-context`.

export const DOCS_CONTEXT = `# speckit-security documentation corpus

This is the complete grounding corpus for the speckit-security docs chat.
It contains every docs page and article as of build time. Cite URLs when
answering. If the answer is not in this corpus, say so plainly.

## DOCS

=== DOCS PAGE: Agent Compatibility ===
URL: /docs/agent-compatibility
Description: Which AI agents are verified hands-on with speckit-security, and which are inferred from Spec Kit's supported list.
\`speckit-security\` is **agent-neutral**, the extension ships
generic Markdown command files and Spec Kit handles the translation
into each AI agent's native format at install time.

## Verified end-to-end

These agents have been smoke-tested with a full install cycle:
\`specify init --ai <agent>\`, \`specify extension add --dev ...\`,
\`specify extension list\`, and execution of the \`gate-check.sh\` script
from inside the installed project.

| Agent | Install location | Format |
|---|---|---|
| **Claude Code** | \`.claude/skills/speckit-tekimax-security-*/SKILL.md\` | Markdown skill with frontmatter |
| **OpenCode** | \`.opencode/command/speckit.tekimax-security.*.md\` | Markdown command |
| **GitHub Copilot** | \`.github/agents/*.agent.md\` + \`.github/prompts/*.prompt.md\` | Agent + prompt files |
| **Gemini CLI** | \`.gemini/commands/speckit.tekimax-security.*.toml\` | TOML command |
| **Cursor** | \`.cursor/skills/speckit-tekimax-security-*/SKILL.md\` | Markdown skill |

All eight \`speckit-security\` commands register cleanly on each
agent, and the gate-check script runs end-to-end after install.

## Supported by Spec Kit (inferred)

These agents are listed in \`specify init --ai <name>\` but haven't
been hands-on tested with \`speckit-security\`. They should work
because Spec Kit handles the translation layer and the extension
provides the same agent-neutral Markdown that it translates for the
verified agents above.

- \`auggie\`
- \`bob\`
- \`codebuddy\`
- \`codex\`
- \`forge\`
- \`iflow\`
- \`junie\`
- \`kilocode\`
- \`kimi\`
- \`kiro-cli\`
- \`pi\`
- \`qodercli\`
- \`qwen\`
- \`roo\`
- \`shai\`
- \`tabnine\`
- \`trae\`
- \`vibe\` (Mistral Vibe)
- \`windsurf\`
- \`generic\` (fallback for unsupported agents)

If you try one of these and it works, please open a PR upstream to
move it into the "Verified" table. If it doesn't work, please open
an issue with the exact \`specify init\` and \`specify extension add\`
output.

## Requirements regardless of agent

- **Spec Kit** \`>= 0.1.0\` installed via \`uv tool install specify-cli\`
- **Bash** (macOS + Linux supported; Windows requires WSL or Git Bash)
- **Python 3**, used by helper scripts for JSON parsing and template
  substitution

## Testing on your agent of choice

\`\`\`bash
# 1. Init a project with your target agent
specify init test-app --ai <agent-name> --no-git

# 2. Install the extension
cd test-app
specify extension add --dev /path/to/speckit-security

# 3. Verify registration
specify extension list
# Should show: Commands: 8 | Hooks: 5 | Status: Enabled

# 4. Verify the commands were translated into the agent's format
specify extension info tekimax-security

# 5. Run the gate-check script directly against a sample spec
#    (it requires a real spec path, so create a stub first)
mkdir -p .specify/specs
cat > .specify/specs/F-000-smoke.md <<'EOF'
## Data Contract
## Security / Threat Model
EOF
bash .specify/extensions/tekimax-security/scripts/bash/gate-check.sh \\
  .specify/specs/F-000-smoke.md 2>&1 || true
\`\`\`

If step 3 shows \`Commands: 8 | Hooks: 5 | Status: Enabled\` and
step 5 runs the gate script (even if it reports gate failures on
the stub spec), the agent is functionally supported.

## Reporting incompatibilities

- **Open an issue** at https://github.com/TEKIMAX/speckit-security/issues
- **Include** the agent name, spec-kit version, OS, and the exact
  output of \`specify extension add --dev\` and \`specify extension list\`
- **Do not** include prompts or conversation snippets, just the
  commands you ran and their output

---

=== DOCS PAGE: Commands ===
URL: /docs/commands
Description: The eight slash commands speckit-security adds to Spec Kit.
\`speckit-security\` adds **eight slash commands** to whichever AI agent
you're using. Every command is an agent-neutral Markdown file under
\`commands/\` in the extension repo, Spec Kit translates each one into
the active agent's native format on install.

| Command | One-line purpose |
|---|---|
| \`data-contract\` | Declare sources, schemas, PII strategy, bias audit, drift thresholds |
| \`threat-model\` | Generate a STRIDE threat model for the active spec |
| \`model-governance\` | Pin model version, define eval baselines, write rollback plan |
| \`guardrails\` | Generate versioned system prompt + guardrail YAML for AI features |
| \`gate-check\` | Run all six gates against the active spec, emit verdict |
| \`audit\` | Post-implementation scan, inline prompts, secrets, direct SDKs |
| \`red-team\` | Generate adversarial scenarios; \`--run\` hits staging automatically |
| \`install-rules\` | Install dev rules into docs, constitution, and agent context file |

## Naming convention

All commands live under the \`speckit.tekimax-security.*\` namespace:

\`\`\`
/speckit.tekimax-security.data-contract
/speckit.tekimax-security.threat-model
/speckit.tekimax-security.model-governance
/speckit.tekimax-security.guardrails
/speckit.tekimax-security.gate-check
/speckit.tekimax-security.audit
/speckit.tekimax-security.red-team
/speckit.tekimax-security.install-rules
\`\`\`

This follows Spec Kit's extension command naming pattern:
\`speckit.{extension-id}.{command-name}\`.

## Which commands fire automatically

Five of the eight commands are wired to Spec Kit phase hooks and fire
automatically. Three are manual-only, you invoke them when you need
them.

### Automatic (via hooks)

- \`data-contract\` fires after \`/speckit.specify\` (optional, prompts)
- \`threat-model\` fires after \`/speckit.plan\` (optional, prompts)
- \`gate-check\` fires before \`/speckit.implement\` (**blocks on failure**)
- \`audit\` fires after \`/speckit.implement\` (**blocks on critical findings**)
- \`red-team\` fires before \`/speckit.analyze\` (optional, prompts)

### Manual

- \`model-governance\`, run once at DESIGN time when adding an AI feature
- \`guardrails\`, run once when adding an AI feature
- \`install-rules\`, run once at project setup

The three optional-prompt hooks (\`data-contract\`, \`threat-model\`,
\`red-team\`) can also be invoked manually if you opt out of the
prompts or want to re-run them later.

## Skipping a hook

To skip an optional hook without disabling the extension, answer "no"
at the prompt. To skip a required hook (gate-check, audit), you have
to either:

1. Fix the issue the gate is catching, or
2. Temporarily disable the extension with \`specify extension disable tekimax-security\`
3. Edit the installed \`extension.yml\` to make the hook optional

See [Customization](/docs/customization) for the long form.

---

=== DOCS PAGE: Customization ===
URL: /docs/customization
Description: Config file, template overrides, hook toggling, allowlists, and environment variables.
\`speckit-security\` is designed to be vendor-agnostic. You can adapt
it to your team's conventions, tools, and policies without forking
the repo. This page walks through every supported customization
point in v0.2.5.

  **What the scripts actually read from the config:**

  - ✅ \`red_team.staging_url\`
  - ✅ \`red_team.max_rps\` (new in v0.2.5)
  - ✅ \`audit.secret_patterns\` (extends built-ins; new in v0.2.5)
  - ✅ \`audit.inline_prompt_patterns\` (extends built-ins; new in v0.2.5)
  - ✅ \`audit.allowlist.stack_direct_sdk\` (extends built-ins; new in v0.2.5)
  - ⏳ \`required_sections\` — still hardcoded (Gate A/B header text)
  - ⏳ \`audit.file_scope\` — still hardcoded
  - ⏳ \`red_team.never_run_against\` — hardcoded on purpose (defense in depth)
  - 🛈 \`enforcement\`, \`stack.*\` — informational, read by humans
    and by Spec Kit's hook runtime (not the individual scripts)

  User-supplied patterns and allowlist entries are **additive**:
  they extend the built-in defaults rather than replacing them. A
  missing config file means full built-in coverage, so adoption is
  safe by default.

  **No plugin system yet.** v0.2.5 does not expose a formal plugin
  system for registering custom commands, gates, or audit checks.
  That's a planned feature. For now, the customization paths below
  cover every real adjustment you can make today.

## 1. Configuration file

The primary customization surface is per-project:

\`\`\`
.specify/extensions/tekimax-security/tekimax-security-config.yml
\`\`\`

Copy the template after installing the extension:

\`\`\`bash
cp .specify/extensions/tekimax-security/config/tekimax-security-config.template.yml \\
   .specify/extensions/tekimax-security/tekimax-security-config.yml
\`\`\`

### Enforcement mode

\`\`\`yaml
enforcement: warn        # warn = hooks advise but never block
                         # strict = hooks block on any gate failure
\`\`\`

  The \`enforcement\` field is read by spec-kit's hook runtime, not by
  the individual scripts. Even in \`warn\` mode, \`gate-check.sh\` and
  \`audit.sh\` still exit non-zero on failure when run directly, the
  \`enforcement\` flag controls whether the hook itself blocks the
  calling phase transition.

### Stack declarations

These are purely informational today: the scripts don't read them.
They document what your team uses so threat models, templates, and
spec authors can reference the right tools. Treat them as metadata
for humans and AI agents reading the config, not as enforcement
knobs.

\`\`\`yaml
stack:
  ai_gateway: <your-ai-gateway>
  guardrails: <your-guardrail-provider>
  pii_encryption: field-level-encryption
  rbac: <your-rbac-provider>
  runtime: <your-runtime>
  schema: zod
  storage: <your-storage>
\`\`\`

### Required spec sections (planned)

The intended config declares which sections a feature spec must
contain:

\`\`\`yaml
required_sections:
  - "Data Contract"
  - "AI Integration"
  - "Security"
  - "Verification"
\`\`\`

⏳ **Not yet read by the scripts.** Today \`gate-check.sh\` hardcodes
the section names it looks for (\`## Data Contract\` /
\`## 2. Data Contract\`, \`## Security / Threat Model\` /
\`## Security\`). To add a new required section today, edit the
\`check_section\` calls in \`gate-check.sh\` directly, or fork the
repo. Config-driven read-back is planned for a later release.

## 2. Environment variables

The bash scripts read these environment variables:

| Variable | Read by | Purpose |
|---|---|---|
| \`SPECKIT_PHASE\` | \`gate-check.sh\` | Phase label in the gate-log JSONL entry (default: \`before_implement\`) |
| \`SPECKIT_TEKIMAX_SECURITY_STAGING_URL\` | \`red-team-run.sh\` | Staging endpoint for the red-team runner |
| \`SPECKIT_TEKIMAX_SECURITY_MAX_RPS\` | \`red-team-run.sh\` | Rate limit for the runner (default: 10) |

## 3. Template overrides

\`speckit-security\` ships seven reference templates under \`templates/\`.
You can override any of them without touching the extension by using
Spec Kit's standard template resolution stack:

1. **Project-local overrides**, \`.specify/templates/overrides/\`
2. **Installed template packs**, \`.specify/templates/packs/<pack-id>/\`
3. **Extension-provided templates**, \`.specify/extensions/tekimax-security/templates/\`
4. **Core templates**

To override the STRIDE threat model template:

\`\`\`bash
mkdir -p .specify/templates/overrides
cp .specify/extensions/tekimax-security/templates/threat-model-stride.md \\
   .specify/templates/overrides/threat-model-stride.md
# edit the copy to match your conventions
\`\`\`

The AI agent will pick up your version on the next
\`/speckit.tekimax-security.threat-model\` run.

## 4. Allowlisting direct SDK imports

The post-implementation audit flags direct model SDK imports outside
your AI gateway layer. By default any file whose path contains
\`src/ai/gateway\` is allowed. You can extend that list via config:

\`\`\`yaml
audit:
  allowlist:
    stack_direct_sdk:
      - "src/platform/ai-proxy"
      - "packages/gateway"
\`\`\`

Entries are **substring matches** against the file path, so
\`src/platform/ai-proxy\` matches both \`src/platform/ai-proxy.ts\`
and \`src/platform/ai-proxy-test.ts\`. The built-in \`src/ai/gateway\`
entry stays active — user entries extend, they don't replace.

The allowlist is also honored by Gate F's inline-prompt check:
files under an allowlisted path can reference inline system
prompts legitimately (because they're part of the gateway), so
they won't trip Gate F.

## 5. Adjusting secret and inline-prompt patterns

Both \`gate-check.sh\` and \`audit.sh\` ship a built-in set of secret
and inline-prompt patterns that cover the most common AWS, GCP,
GitHub, Slack, and Stripe tokens, PEM private keys, and assistant
system-prompt markers. Add your own extensions in config:

\`\`\`yaml
audit:
  inline_prompt_patterns:
    - "// PROMPT-START"           # internal marker your team uses
    - "ASSISTANT_PROMPT_V[0-9]"

  secret_patterns:
    - "ACME_PROD_[0-9a-z]{24}"     # company-internal token prefix
    - "INTERNAL_BEARER_"
\`\`\`

User entries are **additive**: they extend the built-in alternation
rather than replacing it, so you keep full default coverage plus
your custom rules. Patterns are ERE (extended regex), same as
\`grep -E\`.

\`audit.file_scope\` is not yet honored; the scripts still use a
fixed set of \`grep --include\` flags (\`*.ts\`, \`*.tsx\`, \`*.js\`,
\`*.jsx\`, \`*.py\`, and \`*.env*\` for the audit secret scan). File
scope customization is tracked as a follow-up.

## 6. Red team runner configuration

\`\`\`yaml
red_team:
  staging_url: "\${SPECKIT_TEKIMAX_SECURITY_STAGING_URL}"
  max_rps: 10
  never_run_against:
    - "prod"
    - "production"
\`\`\`

What the script honors:

- ✅ \`red_team.staging_url\`, read from config. The env var
  \`SPECKIT_TEKIMAX_SECURITY_STAGING_URL\` takes precedence if both
  are set.
- ✅ \`red_team.max_rps\`, read from config (new in v0.2.5). The env
  var \`SPECKIT_TEKIMAX_SECURITY_MAX_RPS\` takes precedence. Default
  is \`10\` if neither is set.
- 🛈 \`red_team.never_run_against\`, **not read from config on
  purpose**. The script enforces a hardcoded regex refusal on
  \`(^|[^a-z])prod([^a-z]|$)\` and \`production\` as a defense-in-depth
  measure — making this user-overridable would let a misconfigured
  project accidentally fire scenarios at prod.

  **Safety guardrail:** \`red-team-run.sh\` refuses any URL matching
  \`(^|[^a-z])prod([^a-z]|$)|production\`. Your staging URL must not
  contain those tokens. This is enforced in the script itself
  (\`red-team-run.sh:47\`) and cannot be bypassed via config.

## 7. Enabling / disabling hooks

### Disable one hook by making it interactive

Edit \`.specify/extensions/tekimax-security/extension.yml\` and change
\`optional: false\` to \`optional: true\` for the hook you want to
suppress:

\`\`\`yaml
hooks:
  before_implement:
    command: "speckit.tekimax-security.gate-check"
    optional: true   # was false, now prompts instead of auto-running
\`\`\`

This edits the installed copy in \`.specify/\`, not the upstream repo.
Reinstalling the extension resets the change.

### Disable the entire extension temporarily

\`\`\`bash
specify extension disable tekimax-security
# ... work without gates ...
specify extension enable tekimax-security
\`\`\`

### Remove the extension entirely

\`\`\`bash
specify extension remove tekimax-security
\`\`\`

## 8. Fork or write a sibling extension

If configuration isn't enough:

- **Fork:** \`gh repo fork TEKIMAX/speckit-security --clone\` and
  modify. Please also open an issue upstream so broadly useful
  changes can be merged back.
- **Sibling extension:** write your own Spec Kit extension that
  coexists with \`speckit-security\`. See the
  [Spec Kit Extension Development Guide](https://github.com/github/spec-kit/blob/main/extensions/EXTENSION-DEVELOPMENT-GUIDE.md).

---

=== DOCS PAGE: Development Rules ===
URL: /docs/development-rules
Description: The opinionated engineering discipline speckit-security enforces for contributors and ships as a template for users.
\`speckit-security\` ships with **two versions** of the development
rules:

- **Contributor rules**, [docs/DEVELOPMENT-RULES.md](https://github.com/TEKIMAX/speckit-security/blob/main/docs/DEVELOPMENT-RULES.md)
  in the repo. Apply to anyone contributing to the extension itself.
- **User template**, [templates/development-rules.md](https://github.com/TEKIMAX/speckit-security/blob/main/templates/development-rules.md).
  Installed into your project by \`/speckit.tekimax-security.install-rules\`
  so your team inherits the same discipline.

Both versions cover the same nine sections; the user template is
stack-agnostic and designed to be customized per project.

## The nine sections

1. **Commit message rules**, describe the change, not the process.
   No AI attribution, no conversation context, no scrub history.
2. **File structure rules**, hooks stay in hooks, scripts in
   \`scripts/\`, templates in \`templates/\`, tests in \`tests/\`, docs in
   \`docs/\`.
3. **Code organization and reuse**, DRY. Extract helpers when a
   function exceeds 30 lines or does more than one thing.
4. **File length and complexity**, target sizes per file type,
   hard ceilings before splitting.
5. **Naming conventions**, files, functions, variables, env vars.
6. **Inline documentation**, comment *why*, not *what*.
7. **Unit test rules**, every bug fix lands with a regression test,
   incremental coverage, one-command runnable.
8. **Readability and maintainability**, one idea per line, early
   returns, no magic numbers, readable at 3 AM.
9. **Review checklist**, eleven items before opening a PR.

## Runtime enforcement

Installing the rules with \`/speckit.tekimax-security.install-rules\`
writes to **three targets** so they actually bind the AI agent:

1. \`docs/DEVELOPMENT-RULES.md\`, full human-readable reference
2. \`.specify/memory/constitution.md\`, Spec Kit constitution, read by
   every spec-kit-aware AI agent at session start
3. Agent-specific context file (auto-detected from
   \`.specify/init-options.json\`):

| Agent | File |
|---|---|
| \`claude\` | \`CLAUDE.md\` |
| \`copilot\` | \`.github/copilot-instructions.md\` |
| \`gemini\` | \`GEMINI.md\` |
| \`cursor\` / \`cursor-agent\` | \`.cursorrules\` |
| \`windsurf\` | \`.windsurfrules\` |
| \`opencode\`, \`codex\`, \`kiro-cli\`, everything else | \`AGENTS.md\` |

The script is idempotent, running it twice does not duplicate the
\`## Development Rules\` section. Pass \`--force\` to replace an existing
section.

## Why this matters

Writing rules to a \`docs/\` file only works if a human or agent
explicitly reads that file. By also writing to the spec-kit
constitution and the agent context file, the rules become part of
every AI agent's system context at session start. The agent
inherits the discipline automatically for every conversation,
without the human having to remind it.

## Running the installer

From the AI agent:

\`\`\`
/speckit.tekimax-security.install-rules
\`\`\`

From the terminal directly:

\`\`\`bash
bash .specify/extensions/tekimax-security/scripts/bash/install-rules.sh
\`\`\`

Optional flags:

- \`--docs <path>\`, override the default \`docs/DEVELOPMENT-RULES.md\` target
- \`--project-name <name>\`, override project name detection
- \`--force\`, replace an existing \`## Development Rules\` section

See [\`/speckit.tekimax-security.install-rules\`](/docs/commands/install-rules)
for the full command reference.

---

=== DOCS PAGE: FAQ ===
URL: /docs/faq
Description: Common questions about speckit-security, what it does, what it doesn't, and who it's for.
## Does it replace GitHub Spec Kit?

No. \`speckit-security\` is a Spec Kit **extension**, it installs on
top of Spec Kit and adds security gates to Spec Kit's existing
phases. You still need Spec Kit (\`specify\` CLI) to use it.

## Is this a complete security solution?

**No, and it's not trying to be.** \`speckit-security\` catches a
specific class of issues at a specific point in the lifecycle: it
enforces that feature specs declare the required security sections,
that model versions are pinned, that guardrail configs exist, and
that implementation code doesn't contain inline prompts, committed
secrets, or direct SDK imports outside an allowlisted gateway layer.

That's a meaningful subset of what production AI security requires.
It is **not** a replacement for:

- Continuous organization-wide compliance monitoring
- SAST / DAST code scanners
- Dependency vulnerability scanning
- Secret rotation and key management
- Network security, WAF, DDoS protection
- Infrastructure hardening
- Employee security training
- Incident response tooling
- Penetration testing by humans
- External security audits

Use it as **one layer** of your broader security program, not as the
whole program. The project is designed to be extended, see
[Customization](/docs/customization) for the config, template
override, and sibling-extension paths for adding your own checks.

## Does it work with my AI agent?

Probably yes. Spec Kit supports ~20 AI agents and the extension is
agent-neutral, so any agent Spec Kit supports should also support
\`speckit-security\`. Five agents are hands-on verified (Claude Code,
OpenCode, Copilot, Gemini CLI, Cursor); the others are inferred.

See [Agent Compatibility](/docs/agent-compatibility) for the full
matrix and how to test your own agent.

## Does it work on Windows?

Indirectly. The bash scripts (\`gate-check.sh\`, \`audit.sh\`,
\`red-team-run.sh\`, \`install-rules.sh\`) require POSIX bash, so
Windows users need WSL or Git Bash. The Spec Kit CLI itself runs
fine on Windows, but the check scripts won't.

## Will it slow me down?

The gates add friction at phase transitions, that's the point.
Without them you ship faster in the short term and pay interest in
debt, incidents, and rewrites later. With them you ship slightly
slower in the short term and avoid the compounding cost.

Practically, on a well-prepared spec, \`gate-check.sh\` runs in under
a second and \`audit.sh\` runs in under two seconds.

## What happens if a gate fails?

In \`strict\` mode, the hook blocks the phase transition. You either:

1. Fix the issue the gate is catching, or
2. Document it as deferred debt in the spec's \`§8 Deferred / Debt\`
   section with a remediation plan, or
3. Temporarily disable the extension (\`specify extension disable
   tekimax-security\`) if you have a legitimate reason to bypass

In \`warn\` mode, the hook still reports the failure but does not
block.

## Can I use this without spec-driven development?

Yes, but the value is lower. The gates are designed to run at
SPECIFY, DESIGN, IMPLEMENT, and VERIFY transitions. If you don't
write specs, you only get the post-implementation \`audit.sh\` checks
(inline prompts, secrets, direct SDK imports). That's still
valuable but it's about 20% of what the extension offers.

## Can I add my own gates or checks?

The intended paths today are:

1. **Config-level overrides**, edit
   \`.specify/extensions/tekimax-security/tekimax-security-config.yml\`
   to extend the built-in secret patterns, inline-prompt patterns,
   and direct-SDK allowlist. User entries are additive, so you
   keep the defaults plus your custom rules. See
   [Customization](/docs/customization) for the full list of keys
   the scripts actually read and which are still hardcoded.
2. **Template overrides**, drop replacement templates into
   \`.specify/templates/overrides/\` so your team's spec and guardrail
   templates are used instead of the bundled ones.
3. **Fork the extension**, modify or add bash scripts directly,
   then install with \`specify extension add --dev\` from your fork.
   Please also open an issue upstream if the change is broadly
   useful so it can be merged back.
4. **Sibling extension**, write a second Spec Kit extension that
   coexists with \`speckit-security\` and hooks into the same
   lifecycle phases. Both extensions run their own gates.

A formal plugin system (register a custom gate via config, no fork
needed) is planned for a later release. If you have a concrete use
case, **please open an issue** describing what you need, the API
will be shaped by real demand.

See [Customization](/docs/customization) for the full details.

## How do I contribute?

See [CONTRIBUTING.md](https://github.com/TEKIMAX/speckit-security/blob/main/CONTRIBUTING.md)
for the issue-first workflow, dev setup, and the development rules
PRs must follow. Non-negotiable rules are listed in
[DEVELOPMENT-RULES.md](https://github.com/TEKIMAX/speckit-security/blob/main/docs/DEVELOPMENT-RULES.md).

## Where do I report a vulnerability?

**security@tekimax.com**, see
[SECURITY.md](https://github.com/TEKIMAX/speckit-security/blob/main/SECURITY.md)
for the responsible disclosure policy, scope, and response SLAs. Do
**not** open a public issue for security reports.

---

=== DOCS PAGE: Getting Started ===
URL: /docs/getting-started
Description: Install Spec Kit, install the extension, and run your first gated feature in 10 minutes.
## Prerequisites

- **macOS or Linux** (Windows via WSL or Git Bash)
- [\`uv\`](https://github.com/astral-sh/uv), \`brew install uv\`
- **git** and **bash** (both already present on macOS / most Linux)
- An AI agent supported by Spec Kit, Claude Code, Copilot, Gemini CLI,
  Cursor, OpenCode, Windsurf, or one of 15+ others

## 1. Install Spec Kit

\`\`\`bash
uv tool install specify-cli --from git+https://github.com/github/spec-kit.git
specify version
\`\`\`

## 2. Clone the extension

You only need to do this once per machine. The extension is installed
in dev mode from a local clone, no npm install required.

\`\`\`bash
mkdir -p ~/tekimax && cd ~/tekimax
git clone https://github.com/TEKIMAX/speckit-security.git
\`\`\`

## 3. Initialize Spec Kit inside your project

\`speckit-security\` works in any Spec Kit project. You can start a
new project or add Spec Kit to an existing one.

### New project

\`\`\`bash
specify init my-ai-app --ai claude
cd my-ai-app
\`\`\`

### Existing project (e.g. a Vite app)

\`\`\`bash
cd ~/path/to/your-existing-project
specify init . --ai claude
\`\`\`

Replace \`claude\` with your agent of choice: \`copilot\`, \`gemini\`,
\`cursor-agent\`, \`opencode\`, \`windsurf\`, etc.

## 4. Install the extension

\`\`\`bash
specify extension add --dev ~/tekimax/speckit-security
specify extension list
\`\`\`

You should see:

\`\`\`
✓ TEKIMAX Secure SDD (v0.2.6)
    Security-first extension for Spec Kit
    Commands: 8 | Hooks: 5 | Status: Enabled
\`\`\`

## 5. Copy the config template

\`\`\`bash
cp .specify/extensions/tekimax-security/config/tekimax-security-config.template.yml \\
   .specify/extensions/tekimax-security/tekimax-security-config.yml
\`\`\`

The defaults are safe. Customize later, see
[Customization](/docs/customization).

## 6. Install development rules (optional but recommended)

\`\`\`bash
bash .specify/extensions/tekimax-security/scripts/bash/install-rules.sh
\`\`\`

This writes a \`DEVELOPMENT-RULES.md\` into your project, appends the
rules to \`.specify/memory/constitution.md\` (so every AI agent reads
them at session start), and writes the short rules block to your
agent-specific context file (\`CLAUDE.md\`, \`AGENTS.md\`, etc.).

## 7. Use it in your AI agent

Open your project in Claude Code, Copilot, Cursor, or whichever agent
you initialized with. New slash commands are available:

\`\`\`
/speckit.specify          add user authentication with passkeys
                          ← after_specify hook prompts data-contract
/speckit.plan
                          ← after_plan hook prompts threat-model
/speckit.tasks
/speckit.implement        ← before_implement hook auto-fires gate-check
                          ← after_implement hook auto-fires audit
/speckit.analyze          ← before_analyze hook prompts red-team
\`\`\`

The \`before_implement\` hook runs \`gate-check.sh\` and blocks on any
hard failure. The \`after_implement\` hook runs \`audit.sh\` and blocks
on any critical finding. The other three hooks (\`after_specify\`,
\`after_plan\`, \`before_analyze\`) are optional and prompt you before
running.

## 8. Verify the scripts work directly

You can run the gate-check and audit scripts from your terminal
directly, no AI agent required:

\`\`\`bash
bash .specify/extensions/tekimax-security/scripts/bash/gate-check.sh \\
  .specify/specs/F-001-my-feature.md

bash .specify/extensions/tekimax-security/scripts/bash/audit.sh
\`\`\`

Useful for pre-commit hooks, CI steps, and manual spot checks.

## What you just got

\`\`\`
my-ai-app/
├── .specify/
│   ├── memory/constitution.md      ← Rules read by every agent
│   ├── specs/                       ← Your feature specs land here
│   └── extensions/tekimax-security/ ← Full extension
├── .claude/skills/                  ← 8 speckit-security skills
│                                      (or .cursor/skills/, .opencode/command/, etc.)
├── docs/DEVELOPMENT-RULES.md        ← Human-readable rules
├── CLAUDE.md                        ← Short rules block for Claude
└── (your existing project files, untouched)
\`\`\`

## Next steps

---

=== DOCS PAGE: How It Works ===
URL: /docs/how-it-works
Description: Six gates, five hooks, eight commands and how they fit into Spec Kit's lifecycle.
## The SDD lifecycle with speckit-security wired in

Spec Kit's native lifecycle has five phases: **specify**, **plan**,
**tasks**, **implement**, **analyze**. \`speckit-security\` layers six
gates on top of those phases via Spec Kit's hook system.

The \`after_specify\` and \`after_plan\` hooks run **commands** that
help the author *write* the data contract and threat model. The
gates themselves (A–F) are then all executed by \`gate-check.sh\` at
the \`before_implement\` hook — that's the single blocking step.
\`audit.sh\` runs at \`after_implement\` for the post-code scan, and
\`red-team\` runs at \`before_analyze\`.

## The six gates

Each gate is an actual check run by a real bash script, not a
checkbox on a form. Gates emit pass / fail / skip verdicts and
append a JSONL entry to an append-only gate log.

### Gate A, Data Contract

Runs three checks against the active spec and its schemas:

1. The spec contains a \`## 2. Data Contract\` or \`## Data Contract\` section
2. A Zod schema file exists at \`src/schemas/<slug>.ts\`
3. The schema file does not contain \`z.any()\` (which bypasses type safety)

Blocks if any check fails. **Note:** the gate verifies the section
and schema file exist, it does not parse the content of the section
or enforce what's inside it. The reviewer is responsible for
validating that PII, bias, drift, and retention policies are actually
declared.

### Gate B, Threat Model

Runs two checks:

1. The spec contains a \`## Security / Threat Model\` section (or a
   \`## Security\` section that mentions \`STRIDE\` or \`Spoofing\`)
2. No \`[UNMITIGATED]\` markers exist adjacent to \`High\` or \`Critical\`
   severity strings in the spec

Blocks if the section is missing or if the regex
\`[UNMITIGATED].*(High|Critical)\` matches.

### Gate C, Model Governance

Only applies to features with an AI integration (detected by the
presence of \`AI Integration\` or \`model:\` in the spec). Runs two
checks:

1. The spec does not contain \`latest\` (anywhere) or \`"stable"\` (with
   quotes), both indicate an unpinned model version
2. The spec contains the word \`Rollback\` (case-insensitive)

Blocks on unpinned versions or missing rollback mention. **Note:**
the gate verifies the rollback *mention*, it does not parse the
rollback plan to check triggers, target versions, or time budgets.

### Gate D, Guardrails

Only runs when Gate C did not skip. Four checks:

1. \`prompts/guardrails/<slug>.yml\` exists
2. \`prompts/system/<slug>.md\` exists
3. The YAML contains \`blocked_patterns:\`
4. The YAML contains \`redact_patterns:\`

Blocks if any file is missing or if either pattern section is absent
from the guardrail YAML.

### Gate E, Red Team

Checks that a file matching \`red-team/RT-*-<slug>.md\` exists. Skips
with a warning if no file is found (red team is a VERIFY-phase
activity and not required at \`before_implement\` time).

The separate \`red-team-run.sh\` helper reads that report file, parses
scenarios from it, and POSTs them to a staging endpoint with safety
guards: refuses URLs matching \`prod\`/\`production\`, rate-limits to
\`max_rps\` (default 10), and injects an \`X-Red-Team\` header. That
script is triggered by the \`red-team\` command with the \`--run\` flag.

### Gate F, Inline Content Scan

Three checks, in order:

1. **Inline prompts**, greps \`src/**/*.{ts,tsx,js,jsx,py}\` for
   patterns like \`you are a\`, \`as an ai\`, \`<|system|>\`
   (case-insensitive). Files with \`gateway\` in their path are
   excluded so the gateway client itself can reference model SDKs.
2. **Committed secrets**, greps \`*.ts\`, \`*.tsx\`, \`*.js\`, \`*.py\`
   files across the repo (excluding \`node_modules/\`, \`.git/\`,
   \`.next/\`, \`out/\`, \`.source/\`, \`.wrangler/\`, and \`dist/\`) for
   \`sk_live_\`, \`sk_test_\`, \`BEGIN (RSA|EC|OPENSSH) PRIVATE KEY\`,
   \`ghp_\` (GitHub personal tokens), \`AKIA[A-Z0-9]{16}\` (AWS), and
   \`AIza[A-Za-z0-9_-]{35}\` (Google). The post-implementation
   \`audit.sh\` scans an even wider set, including \`xoxb-\` Slack
   tokens, \`gho_\`/\`ghs_\`, \`DSA\` and \`ENCRYPTED\` private keys, and
   also inspects \`.env*\` files directly.
3. **\`.env\` in git**, runs \`git ls-files\` and checks for any path
   matching \`^\\.env(\\..*)?$\`.

Blocks if any of the three checks finds a hit.

**Note:** direct model SDK imports outside the gateway are checked
by \`audit.sh\`, not Gate F. Gate F is about inline prompts, secrets,
and committed \`.env\` only. See the [audit command](/docs/commands/audit)
for the direct-SDK-import check.

## The five hooks

Hooks are how the gates fire automatically without the developer
remembering to run them. Each hook is registered in \`extension.yml\`
under the \`hooks:\` block.

| Hook | Command it runs | Blocking? |
|---|---|---|
| \`after_specify\` | \`data-contract\` | Optional, prompts the user |
| \`after_plan\` | \`threat-model\` | Optional, prompts the user |
| \`before_implement\` | \`gate-check\` | **Required, blocks on failure** |
| \`after_implement\` | \`audit\` | **Required, blocks on critical findings** |
| \`before_analyze\` | \`red-team\` | Optional, prompts the user |

## The eight commands

| Command | Purpose | Hook? |
|---|---|---|
| \`/speckit.tekimax-security.data-contract\` | Declare data contract (schemas, PII, bias, drift, retention) | \`after_specify\` |
| \`/speckit.tekimax-security.threat-model\` | Generate STRIDE threat model | \`after_plan\` |
| \`/speckit.tekimax-security.model-governance\` | Pin model version, define eval criteria, rollback plan | manual |
| \`/speckit.tekimax-security.guardrails\` | Generate input/output guardrail config | manual |
| \`/speckit.tekimax-security.gate-check\` | Run all gates and emit verdict | \`before_implement\` |
| \`/speckit.tekimax-security.audit\` | Post-implementation scan | \`after_implement\` |
| \`/speckit.tekimax-security.red-team\` | Generate adversarial scenarios and run them | \`before_analyze\` |
| \`/speckit.tekimax-security.install-rules\` | Install dev rules into docs, constitution, and agent context | manual |

## Append-only gate log

Every gate-check run appends a JSONL entry to
\`.tekimax-security/gate-log.jsonl\`:

\`\`\`json
{"spec":"F-001","phase":"before_implement","verdict":"PASS","ts":"2026-04-13T08:30:00Z","user":"Christian Kaman","gates":{"A":"pass","B":"pass","C":"pass","D":"pass","E":"skip","F":"pass"}}
\`\`\`

Same for \`audit.sh\` → \`.tekimax-security/audit-log.jsonl\`. The log
is append-only by convention, never rewrite or delete entries. This
is the audit trail your compliance reviewer reads.

## Runtime dependencies

The scripts use only standard tools that already ship with macOS
and Linux: \`bash\`, \`grep\`, \`sed\`, \`git\`, and \`python3\`. The shared
\`lib/config.sh\` helper shells out to \`python3\` for a small inline
YAML reader so each script can fall back to config-defined
patterns, allowlists, and thresholds. \`install-rules.sh\` and
\`red-team-run.sh\` also use \`python3\` for JSON handling.

No \`npm install\`. No \`pip install\`. No third-party Python packages,
just the standard library. No language runtime or package manager
beyond what your OS already provides. The full test suite runs in
under a second.

---

=== DOCS PAGE: Overview ===
URL: /docs
Description: A security-first extension for GitHub Spec Kit that catches AI technical debt before code ships.
## What is speckit-security?

\`speckit-security\` is a **community extension** for
[GitHub Spec Kit](https://github.com/github/spec-kit) that adds
**security gates** to the spec-driven development lifecycle. It hooks
directly into Spec Kit's \`after_specify\`, \`after_plan\`, \`before_implement\`,
\`after_implement\`, and \`before_analyze\` phase transitions to catch AI
technical debt at the cheapest point in the lifecycle: at the spec
and artifact level, before \`/speckit.implement\` generates the bulk
of the feature code.

> **Disclaimer:** \`speckit-security\` is an independent, third-party
> extension built and maintained by [TEKIMAX](https://tekimax.com).
> It is **not** officially endorsed, approved, or maintained by GitHub.
> It uses Spec Kit's public extension API and community catalog. GitHub
> and Spec Kit are trademarks of GitHub, Inc.

> **One layer, not the whole program.** \`speckit-security\` is a
> **starting point**, not a complete security solution. It catches a
> specific class of AI-delivery issues at design and commit time. It
> is **extensible**: every check is configurable, every template is
> overridable, and every pattern can be customized per project. Use
> it alongside your other security tooling (SAST, dependency
> scanning, runtime monitoring, compliance platforms), not as a
> replacement for any of them. See
> [Customization](/docs/customization) and the
> [FAQ entry on scope](/docs/faq#is-this-a-complete-security-solution)
> for the details.

## Why it exists

Spec Kit turns specifications into code. It does **not** enforce
security: no threat modeling, no AI guardrails, no red teaming, no
model governance, no audit of inline prompts or committed secrets.

In production AI systems, those are the gaps where compounding
technical debt lives. You ship a feature fast, a month later an
LLM leaks PII through a prompt the reviewer never saw, and suddenly
you're rewriting the whole data pipeline under incident pressure.

\`speckit-security\` closes that loop. It's the security layer that
Spec Kit doesn't ship with, packaged as a first-class extension so
you don't have to fork spec-kit or maintain a parallel CLI.

## What it catches

The gates enforce the *existence* of security controls. They check
that specs contain the required sections, that schema files exist,
that model versions are pinned, that guardrail config is present,
and that code doesn't contain inline prompts or committed secrets.

<div className="wide-table">

| Check | Where enforced | What it does |
|---|---|---|
| **Data Contract section + Zod schema file** | \`gate-check.sh\` Gate A | Blocks if the spec has no \`## Data Contract\` section, the schema file is missing, or the schema uses \`z.any()\`. |
| **STRIDE threat model** | \`gate-check.sh\` Gate B | Blocks if the spec has no \`## Security / Threat Model\` section, or if any threat is marked \`[UNMITIGATED]\` at High or Critical severity. |
| **Model version pinning + rollback plan** | \`gate-check.sh\` Gate C | For AI features: blocks on \`"latest"\` or \`"stable"\` strings and requires a "Rollback" mention in the spec. |
| **Guardrail YAML + system prompt file** | \`gate-check.sh\` Gate D | For AI features: requires \`prompts/guardrails/<slug>.yml\` with both \`blocked_patterns\` and \`redact_patterns\`, plus \`prompts/system/<slug>.md\`. |
| **Red team report presence** | \`gate-check.sh\` Gate E | Checks that \`red-team/RT-*-<slug>.md\` exists. The separate \`red-team-run.sh\` executes the scenarios against staging when invoked with \`--run\`. |
| **Inline prompts + secrets + .env in git** | \`gate-check.sh\` Gate F | Greps \`src/\` for inline system prompt patterns, the whole repo for committed secret patterns (\`sk_live_\`, \`PRIVATE_KEY\`, etc.), and \`git ls-files\` for \`.env\`. |
| **Direct model SDK imports outside the gateway** | \`audit.sh\` (post-implementation) | Greps \`src/\` for \`@google/genai\`, \`@anthropic-ai/sdk\`, and \`openai\` imports outside allowlisted files. |
| **Guardrail version bump on edit** | \`audit.sh\` (post-implementation) | Warns if \`prompts/system/<slug>.md\` or \`prompts/guardrails/<slug>.yml\` was changed without a version bump in the frontmatter. |

</div>

**What the gates do not do:** they don't read the *content* of a PII
strategy, bias audit, or rollback plan. They only verify the
sections or tokens are present. Rich content validation is the
reviewer's job and the AI agent's job, not the script's.

## Six gates, eight commands, five hooks

Gates A–F are enforced by real bash scripts. Every run appends a
JSONL entry to an append-only gate log (\`spec\`, \`phase\`, \`verdict\`,
\`ts\`, \`user\`, per-gate status) so you can reconstruct the decision
trail for compliance review. The scripts run on macOS and Linux
with only the standard Unix tools that ship with the OS, plus
\`python3\` for a couple of helper scripts.

## Design principles

- **Vendor-agnostic, TypeScript-opinionated defaults.** The extension
  enforces the *existence* of security controls (AI gateway,
  guardrails, PII encryption, RBAC, schema validation) without
  requiring specific vendors. The current gate defaults assume a
  TypeScript/Node project: Gate A looks for \`src/schemas/<slug>.ts\`
  (Zod), and the \`audit.sh\` direct-SDK check greps for
  \`@google/genai\`, \`@anthropic-ai/sdk\`, and \`openai\`. Override the
  paths and patterns in \`tekimax-security-config.yml\` for other
  stacks.
- **Agent-neutral.** Ships as a Spec Kit extension, so it works with
  every agent Spec Kit supports: Claude Code, Copilot, Gemini CLI,
  Cursor, OpenCode, Windsurf, and 15+ others. Spec Kit handles the
  per-agent format translation.
- **No package-manager dependencies.** No \`npm install\`, no
  \`pip install\`. Just \`bash\`, \`grep\`, \`sed\`, \`git\`, and \`python3\`
  (all of which every macOS and Linux system ships). No
  third-party Python packages, just the standard library. Runs in
  under a second.
- **Honest alpha.** v0.2.x is alpha and marked alpha. API may change.
  See the [Changelog](https://github.com/TEKIMAX/speckit-security/blob/main/CHANGELOG.md)
  for every release.

## Open source, Apache-2.0

\`speckit-security\` is maintained by [TEKIMAX](https://tekimax.com)
and released under Apache-2.0. Contributions welcome, see
[CONTRIBUTING.md](https://github.com/TEKIMAX/speckit-security/blob/main/CONTRIBUTING.md).

Vulnerabilities: **security@tekimax.com** (see
[SECURITY.md](https://github.com/TEKIMAX/speckit-security/blob/main/SECURITY.md)).

General questions: **support@tekimax.com**.

---

=== DOCS PAGE: Sandbox (Experimental) ===
URL: /docs/sandbox/index
Description: Run speckit-security gate scripts inside a sandboxed environment for defense-in-depth isolation.
> **Experimental.** Everything on this page is exploratory. APIs,
> integration patterns, and supported runtimes may change without
> notice. Do not depend on sandbox support in production CI pipelines
> until it graduates from experimental status.

## Why sandbox?

By default, speckit-security scripts run directly on the host shell.
They have [project-root confinement](/docs/security) via
\`require_inside_project\`, but that's a **check**, not a **boundary**
-- a bug in the scripts or a crafted input could still access the
host filesystem or network.

A sandbox adds a real isolation boundary:

| Layer | What it prevents |
|-------|------------------|
| **Filesystem isolation** | Scripts can only see files you explicitly mount -- no \`/etc\`, no \`~/.ssh\`, no sibling repos |
| **Network disabled** | Gate scripts have no reason to make network calls -- sandbox enforces it at the runtime level |
| **Execution limits** | Malicious spec files cannot trigger infinite loops or fork bombs |
| **Write isolation** | Scripts read your real project files but writes go to an in-memory layer -- the real project is never modified |

## When to use a sandbox

- **Untrusted specs.** Running gate-check against a spec file from an
  external contributor or a pull request you haven't reviewed yet.
- **CI on shared runners.** If your CI runner processes multiple repos,
  sandboxing prevents cross-repo information leakage.
- **Web-based gate runners.** If you build a UI that lets users run
  gate-check from a browser, the sandbox is essential.
- **Defense in depth.** Even if you trust the input, sandboxing limits
  the blast radius of any bug in the scripts themselves.

## When you don't need it

- **Local development.** If you're the only person running the scripts
  on your own machine against your own specs, the built-in
  \`require_inside_project\` confinement is sufficient.
- **Trusted CI.** If your CI only processes your own repo and the
  runner is ephemeral (e.g. GitHub Actions), host isolation is already
  provided by the runner VM.

## Available sandbox runtimes

More runtimes may be added as the ecosystem matures. Contributions
welcome -- see [CONTRIBUTING.md](https://github.com/TEKIMAX/speckit-security/blob/main/CONTRIBUTING.md).

---

=== DOCS PAGE: just-bash ===
URL: /docs/sandbox/just-bash
Description: Run speckit-security gate scripts inside Vercel Labs' just-bash virtual bash environment for filesystem and network isolation.
> **Experimental.** This integration is exploratory. It works for
> a subset of the gate scripts today and has known limitations.
> Do not depend on it in production without testing your specific
> workflow end-to-end.

## What is just-bash?

[just-bash](https://github.com/vercel-labs/just-bash) is a virtual
bash environment by Vercel Labs. It runs ~80 Unix commands
(grep, sed, cat, find, awk, jq, etc.) in a TypeScript process with
an in-memory filesystem. Network access is disabled by default.

It is **not** a full Linux VM. It's a purpose-built shell emulator
designed for AI agents that need a sandboxed execution environment.

**Repository:** [github.com/vercel-labs/just-bash](https://github.com/vercel-labs/just-bash)
**License:** Apache-2.0

## Why use it with speckit-security?

speckit-security scripts normally run directly on the host shell.
The built-in [project-root confinement](/docs/security) validates
file paths, but it's a check, not a boundary. \`just-bash\` adds a
real isolation layer:

- **Filesystem isolation** -- scripts only see files you explicitly
  load. No \`/etc\`, no \`~/.ssh\`, no sibling repos.
- **Network disabled** -- gate scripts cannot make HTTP calls
  (the red-team runner is excluded from sandbox use for this reason).
- **Execution limits** -- configurable caps on loop iterations,
  call depth, and total command count.
- **Write isolation** -- the in-memory filesystem means writes never
  touch the real project.

## Important: this adds a dependency

speckit-security's core scripts have **zero runtime dependencies**
beyond bash, grep, sed, git, and python3 -- all standard OS tools.

Adding \`just-bash\` introduces a **Node.js / npm dependency**. This
is an opt-in choice for teams that want sandbox isolation. The core
scripts continue to work without it. The sandbox wrapper is a
separate entrypoint, not a replacement for the standard scripts.

\`\`\`
# Standard (no deps):        bash scripts/bash/gate-check.sh <spec>
# Sandboxed (requires npm):  node sandbox/run-gate-check.mjs <spec>
\`\`\`

## What works today

Tested against \`just-bash@latest\` in Node.js:

| Command / Feature | Status | Notes |
|---|---|---|
| \`grep -rIlE\` (extended regex, recursive) | Works | Core of Gate F and audit scanning |
| \`grep -ic\`, \`grep -q\`, \`grep -qF\` | Works | Used throughout gate-check |
| \`sed\`, \`cat\`, \`head\`, \`tail\`, \`wc\` | Works | Text processing |
| \`find\`, \`ls\`, \`mkdir\`, \`basename\`, \`dirname\` | Works | File operations |
| \`date -u\` | Works | Timestamps for JSONL |
| Pipes (\`\\|\`), redirections (\`>\`, \`>>\`), \`&&\`, \`\\|\\|\` | Works | Shell plumbing |
| Variable expansion, \`for\` loops, \`if/else\` | Works | Control flow |
| \`echo\`, \`printf\` | Works | Output |
| \`set -euo pipefail\` | Partial | \`set -e\` works, \`pipefail\` behavior may differ |

## What does NOT work today

| Command / Feature | Status | Why |
|---|---|---|
| \`python3\` | Not available | WASM binary requires network download (designed for Vercel Sandbox cloud API) |
| \`git\` | Not available | Not a built-in command |
| \`shasum\` / \`sha256sum\` | Not available | Not a built-in command |
| \`curl\` | Requires network opt-in | Disabled by default (correct for gate scripts, but means red-team runner cannot be sandboxed) |
| \`source\` / \`.\` (sourcing scripts) | Partial | Works for simple scripts, complex sourcing chains may need adjustment |

### Impact on speckit-security scripts

The scripts depend on \`python3\` for:

- **YAML config parsing** (\`lib/config.sh\`)
- **JSONL output** (\`jsonl_append\` / \`jsonl_append_chained\` in \`lib/defaults.sh\`)
- **Path confinement** (\`require_inside_project\` uses \`os.path.realpath\`)
- **Red-team scenario parsing** (\`red-team-run.sh\`)

Without Python, the full gate-check and audit scripts cannot run
inside \`just-bash\` unmodified. The approach below works around this
by pre-parsing config and writing JSONL from the Node.js wrapper.

## Step-by-step: sandboxed gate-check

This walkthrough creates a Node.js wrapper that loads your project
files into \`just-bash\`'s in-memory filesystem and runs a simplified
gate-check. It handles config parsing and JSONL output in JavaScript
instead of Python.

### 1. Install just-bash

\`\`\`bash
cd your-project
npm install just-bash
\`\`\`

### 2. Create the sandbox wrapper

Create \`sandbox/run-gate-check.mjs\`:

\`\`\`javascript
#!/usr/bin/env node
// Sandboxed gate-check runner using just-bash
// Usage: node sandbox/run-gate-check.mjs <spec-path>

const specPath = process.argv[2];
if (!specPath) {
  console.error("usage: node sandbox/run-gate-check.mjs <spec-path>");
  process.exit(2);
}

// --- Load project files into the in-memory filesystem ---------------

const projectRoot = process.cwd();
const files = {};

function loadDir(dir, prefix) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const vpath = prefix + "/" + entry.name;
    if (entry.isDirectory()) {
      const skip = [
        "node_modules", ".git", ".next", "out",
        ".wrangler", "dist", ".source",
      ];
      if (skip.includes(entry.name)) continue;
      loadDir(full, vpath);
    } else if (entry.isFile()) {
      try {
        files[vpath] = readFileSync(full, "utf8");
      } catch {
        // skip binary files
      }
    }
  }
}

loadDir(projectRoot, "");
console.log(\`Loaded \${Object.keys(files).length} files into sandbox\`);

// --- Pre-parse config (replaces python3 config.sh) ------------------

const configPath = ".specify/extensions/tekimax-security/tekimax-security-config.yml";
let userSecretPatterns = [];
let userInlinePatterns = [];
let userGatewayAllowlist = [];

if (files["/" + configPath]) {
  // Minimal YAML list parser for the specific keys we need
  const content = files["/" + configPath];
  const parseList = (key) => {
    const re = new RegExp(
      \`\${key}:\\\\s*\\\\n((?:\\\\s+-\\\\s+.+\\\\n?)*)\`,
    );
    const m = content.match(re);
    if (!m) return [];
    return m[1]
      .split("\\n")
      .map((l) => l.replace(/^\\s*-\\s*/, "").replace(/["']/g, "").trim())
      .filter(Boolean);
  };
  userSecretPatterns = parseList("secret_patterns");
  userInlinePatterns = parseList("inline_prompt_patterns");
  userGatewayAllowlist = parseList("stack_direct_sdk");
}

// --- Inject parsed config as env vars for the bash script -----------

const bash = new Bash({
  files,
  cwd: "/",
  env: {
    HOME: "/",
    SANDBOX: "true",
    // Pass parsed config as env vars so the script doesn't need python3
    USER_SECRET_PATTERNS: userSecretPatterns.join("|"),
    USER_INLINE_PATTERNS: userInlinePatterns.join("|"),
    USER_GATEWAY_ALLOWLIST: userGatewayAllowlist.join(":"),
  },
  executionLimits: {
    maxCallDepth: 50,
    maxCommandCount: 10000,
    maxLoopIterations: 10000,
  },
});

// --- Run a simplified gate-check in the sandbox ---------------------

const specVpath = "/" + relative(projectRoot, resolve(specPath));

// Gate F: inline prompt scan (the most valuable sandbox check)
const inlinePromptRe =
  '([Yy]ou[[:space:]]+are[[:space:]]+(a|an)[[:space:]]+(helpful|AI|assistant|chatbot|expert)|<\\\\|system\\\\|>|<\\\\|im_start\\\\|>system)';

const gateF = await bash.exec(
  \`if [ -d /src ]; then
    hits=$(grep -rIliE '\${inlinePromptRe}' --include="*.ts" --include="*.tsx" --include="*.js" --include="*.py" /src 2>/dev/null || true)
    if [ -n "$hits" ]; then
      echo "FAIL: inline prompts found"
      echo "$hits"
      exit 1
    fi
  fi
  echo "PASS"\`,
);

// Gate A: data contract section
const gateA = await bash.exec(
  \`grep -qF "## 2. Data Contract" \${specVpath} 2>/dev/null || grep -qF "## Data Contract" \${specVpath} 2>/dev/null; echo $?\`,
);

// Gate B: threat model with content
const gateB = await bash.exec(
  \`if grep -qF "## Security / Threat Model" \${specVpath} 2>/dev/null || grep -qF "## Security" \${specVpath} 2>/dev/null; then
    if grep -qE '^\\\\|[[:space:]]*T[0-9]' \${specVpath} 2>/dev/null || grep -qE '^\\\\|[[:space:]]*(Spoofing|Tampering)' \${specVpath} 2>/dev/null; then
      echo "PASS"
    else
      echo "FAIL: STRIDE table has no threat rows"
    fi
  else
    echo "FAIL: missing threat model"
  fi\`,
);

// --- Report ---------------------------------------------------------

console.log("\\n--- Sandboxed Gate Check ---");
console.log(\`Spec: \${specPath}\`);
console.log(\`Gate A (Data Contract): \${gateA.stdout.trim() === "0" ? "PASS" : "FAIL"}\`);
console.log(\`Gate B (Threat Model):  \${gateB.stdout.trim()}\`);
console.log(\`Gate F (Inline Scan):   \${gateF.stdout.trim().split("\\n")[0]}\`);

if (gateF.stdout.includes("FAIL")) {
  console.log("\\nInline prompt findings:");
  console.log(
    gateF.stdout
      .split("\\n")
      .slice(1)
      .map((l) => "  " + l)
      .join("\\n"),
  );
}

// --- Write JSONL to real filesystem (outside sandbox) ---------------

const logDir = join(projectRoot, ".tekimax-security");
mkdirSync(logDir, { recursive: true });
const logPath = join(logDir, "gate-log.jsonl");

// Read previous hash for chain
let prevHash = "genesis";
if (existsSync(logPath)) {
  const lines = readFileSync(logPath, "utf8").trim().split("\\n");
  if (lines.length > 0 && lines[lines.length - 1]) {
    prevHash =
      "sha256:" +
      createHash("sha256")
        .update(lines[lines.length - 1])
        .digest("hex");
  }
}

const verdict =
  gateA.stdout.trim() === "0" &&
  gateB.stdout.trim() === "PASS" &&
  gateF.stdout.trim() === "PASS"
    ? "PASS"
    : "BLOCK";

const entry = JSON.stringify({
  spec: specPath,
  phase: "before_implement",
  verdict,
  ts: new Date().toISOString(),
  user: "sandbox",
  sandbox: "just-bash",
  gates: {
    A: gateA.stdout.trim() === "0" ? "pass" : "fail",
    B: gateB.stdout.trim().startsWith("PASS") ? "pass" : "fail",
    F: gateF.stdout.trim() === "PASS" ? "pass" : "fail",
  },
  prev_hash: prevHash,
});

appendFileSync(logPath, entry + "\\n");

console.log(\`\\nVERDICT: \${verdict}\`);
console.log(\`Gate log: \${logPath}\`);

process.exit(verdict === "PASS" ? 0 : 1);
\`\`\`

### 3. Run it

\`\`\`bash
node sandbox/run-gate-check.mjs .specify/specs/F-001-my-feature.md
\`\`\`

Example output:

\`\`\`
Loaded 132 files into sandbox

--- Sandboxed Gate Check ---
Spec: .specify/specs/F-001-my-feature.md
Gate A (Data Contract): PASS
Gate B (Threat Model):  PASS
Gate F (Inline Scan):   PASS

VERDICT: PASS
Gate log: .tekimax-security/gate-log.jsonl
\`\`\`

### 4. Verify isolation

The sandbox prevents access to anything outside the loaded files:

\`\`\`javascript
// This returns exit 1 — /etc doesn't exist in the sandbox
const r = await bash.exec("cat /etc/passwd");
// r.exitCode === 1
// r.stderr === "cat: /etc/passwd: No such file or directory"

// Network is disabled — curl fails
const r2 = await bash.exec("curl https://example.com");
// r2.exitCode === 1
\`\`\`

## Limitations and caveats

### Gates C, D, E are not covered

The wrapper above demonstrates Gates A, B, and F. Gates C (Model
Governance), D (Guardrails), and E (Red Team) require more
complex file parsing. You can extend the wrapper to add them --
the pattern is the same: run grep/sed commands inside the sandbox
and parse the results in JavaScript.

### No Python in the sandbox

The \`python3\` runtime in \`just-bash\` downloads a CPython WASM
binary over the network. It's designed for the
[Vercel Sandbox API](https://sdk.vercel.ai/docs/ai-sdk-core/sandbox)
cloud environment, not local Node.js. This means:

- \`lib/config.sh\` (YAML parser) does not work inside the sandbox
- \`jsonl_append\` / \`jsonl_append_chained\` do not work inside the sandbox
- \`require_inside_project\` does not work inside the sandbox
  (but isn't needed -- the in-memory filesystem is the confinement)

The wrapper works around this by doing config parsing and JSONL
output in JavaScript instead.

### No git

\`git\` is not a built-in command. Checks that use
\`git ls-files\` (e.g. \`.env committed\` detection) or
\`git config user.name\` need to be handled by the Node.js wrapper.

### Red-team runner cannot be sandboxed

\`red-team-run.sh\` makes HTTP requests to a staging endpoint by
design. Sandboxing it with network disabled would defeat its
purpose. Continue running it directly on the host with the
built-in \`never_run_against\` safety guards.

### Not a full POSIX shell

\`just-bash\` implements ~80 commands, not the full POSIX spec. Some
edge cases in complex \`grep\` flag combinations, \`sed\` expressions,
or shell syntax may behave differently. Always test your specific
scripts.

## Future directions

- **Python support** -- if \`just-bash\` adds offline CPython WASM
  loading, the full gate scripts could run unmodified.
- **Vercel Sandbox API** -- for CI or cloud use cases, the Vercel
  Sandbox API provides the same \`just-bash\` interface with full
  Python support. This would allow running the unmodified scripts
  in a cloud sandbox.
- **Full gate coverage** -- extend the wrapper to cover all six
  gates with JavaScript equivalents of the Python helpers.
- **Pre-built sandbox image** -- package a ready-to-use sandbox
  wrapper as an npm package that users can install alongside
  speckit-security.

## Further reading

- [just-bash README](https://github.com/vercel-labs/just-bash)
- [Vercel Sandbox API docs](https://sdk.vercel.ai/docs/ai-sdk-core/sandbox)
- [speckit-security Security Model](/docs/security) -- the built-in
  confinement and JSONL safety measures that work without any sandbox

---

=== DOCS PAGE: Security Model ===
URL: /docs/security
Description: How speckit-security protects itself, confines scripts to the project directory, and enforces guardrails at every layer.
## Security architecture

\`speckit-security\` operates at two levels:

1. **Feature security** -- the six gates that enforce threat models, data contracts, guardrails, and red teaming on the features *you* build.
2. **Self security** -- the measures that prevent the extension's own scripts from being exploited via path traversal, injection, or tampering.

This page covers both.

---

## Script confinement

Every bash script in \`speckit-security\` is confined to the project
directory. Scripts **cannot read, write, or execute files outside the
project root**, enforced by the \`require_inside_project\` helper in
\`lib/defaults.sh\`.

### How it works

When a script receives a file path argument (e.g. \`gate-check.sh <spec-path>\`),
it resolves the path to its canonical absolute form using Python's
\`os.path.realpath\` (which follows symlinks) and verifies the resolved path
starts with \`$(pwd -P)\` (the physical project root):

\`\`\`bash
require_inside_project "$SPEC_PATH" "spec path"
\`\`\`

If the path escapes the project -- via \`../..\` traversal, absolute
paths like \`/etc/passwd\`, or symlinks pointing outside -- the script
exits immediately with error code 2:

\`\`\`
error: spec path escapes the project root.
  resolved: /etc/passwd
  project:  /home/user/my-project
  speckit-security scripts are confined to the project directory.
\`\`\`

### What is confined

| Script | Input | Confinement |
|--------|-------|-------------|
| \`gate-check.sh\` | \`$1\` (spec file path) | \`require_inside_project\` before any read |
| \`install-rules.sh\` | \`--docs <path>\` argument | \`require_inside_project\` before any write |
| \`audit.sh\` | scans \`src/\` and \`.\` | Hardcoded relative paths, exclusion list for \`node_modules\`, \`.git\`, \`dist\`, \`.next\` |
| \`red-team-run.sh\` | staging URL from config | Regex + \`never_run_against\` config list blocks production URLs |
| \`config.sh\` | config YAML path | Hardcoded by callers to \`.specify/extensions/.../config.yml\` |

### Log files

All log files (gate-log, audit-log, red-team traces) are written to
\`.tekimax-security/\` using hardcoded relative paths that cannot be
overridden by user input.

---

## JSONL injection prevention

Gate verdicts and audit results are written as JSONL (one JSON object
per line). All JSONL output is produced by \`jsonl_append\` in
\`lib/defaults.sh\`, which passes every value through Python's
\`json.dumps\` -- shell metacharacters in git usernames, spec titles, or
red-team scenario text cannot break the JSON structure or inject
shell commands.

\`\`\`bash
# Safe -- values are escaped by Python, not interpolated in bash
jsonl_append "$GATE_LOG" \\
  "user"    "$USER" \\
  "verdict" "$VERDICT"
\`\`\`

---

## Tamper-evident hash chain

Every gate-log entry includes a \`prev_hash\` field containing the
SHA-256 of the previous line (or \`"genesis"\` for the first entry).
This creates a lightweight hash chain: if any past entry is modified,
the chain breaks and the tampering is detectable by recomputing hashes.

\`\`\`jsonl
{"spec": "F-001", "verdict": "PASS", ..., "prev_hash": "genesis"}
{"spec": "F-002", "verdict": "PASS", ..., "prev_hash": "sha256:a1b2c3..."}
\`\`\`

The hash chain provides tamper **detection**. For tamper **proof**
(cryptographic signatures with cosign/ed25519), a signing layer
can be added on top -- see the [TEKIMAX website](https://tekimax.com)
for commercial add-ons.

---

## Guardrail architecture

The guardrail system operates at three layers:

### Layer 1: Spec-time guardrails (Gate D)

The \`/speckit.tekimax-security.guardrails\` command generates two files
per feature:

- \`prompts/guardrails/<slug>.yml\` -- machine-readable config with:
  - \`input.blocked_patterns\` -- strings that reject the request
  - \`output.redact_patterns\` -- regex patterns replaced in model output
  - \`limits.rate_per_user_per_minute\` -- numeric rate limit
  - \`limits.cost_ceiling_usd_per_day\` -- numeric cost ceiling
- \`prompts/system/<slug>.md\` -- versioned system prompt with frontmatter

Gate D in \`gate-check.sh\` verifies all five keys exist and that rate
limit and cost ceiling are numeric (not placeholder text).

### Layer 2: Implementation-time audit (Gate F)

\`audit.sh\` scans the codebase for:

| Check | Severity | What it catches |
|-------|----------|-----------------|
| Inline prompts in \`src/\` | CRITICAL | System prompts hardcoded in source instead of the versioned \`.md\` file |
| Committed secrets | CRITICAL | API keys, private keys, tokens matching known patterns |
| \`.env\` in git | CRITICAL | Environment files tracked by git |
| Direct SDK imports | WARN | Model SDK imports outside the gateway allowlist |
| Guardrail freshness | WARN | Guardrail YAML or system prompt edited without a version bump |
| Guardrail completeness | WARN | Missing \`blocked_patterns\`, \`redact_patterns\`, rate limits, or cost ceilings |

### Layer 3: Runtime guardrails

The guardrail YAML is consumed by your AI gateway middleware at
runtime. \`speckit-security\` enforces the *existence and completeness*
of guardrails -- it does not run a gateway itself. The runtime
enforcement depends on your stack:

- **Input validation** -- the gateway loads \`blocked_patterns\` and
  rejects matching messages before they reach the model
- **Output redaction** -- the gateway loads \`redact_patterns\` and
  replaces PII/sensitive patterns in model responses
- **Rate limiting** -- the gateway enforces \`rate_per_user_per_minute\`
- **Cost ceiling** -- the gateway enforces \`cost_ceiling_usd_per_day\`

For a ready-made gateway client that loads your guardrail YAML at
startup, see the [TEKIMAX website](https://tekimax.com) for
commercial add-ons.

---

## Secret detection

Both \`gate-check.sh\` (Gate F) and \`audit.sh\` scan for committed
secrets using a shared set of patterns defined in \`lib/defaults.sh\`:

| Pattern | What it matches |
|---------|----------------|
| \`sk_live_...\` / \`sk_test_...\` | Stripe API keys |
| \`-----BEGIN ... PRIVATE KEY-----\` | RSA, EC, DSA, OPENSSH, encrypted private keys |
| \`xoxb-...\` | Slack bot tokens |
| \`ghp_...\` / \`gho_...\` / \`ghs_...\` | GitHub personal, OAuth, and server tokens |
| \`AKIA...\` | AWS access key IDs |
| \`AIza...\` | Google API keys |

You can extend these with project-specific patterns in
\`tekimax-security-config.yml\`:

\`\`\`yaml
audit:
  secret_patterns:
    - "my_custom_live_[a-zA-Z0-9]{32,}"
\`\`\`

User patterns are **additive** -- they extend the built-in defaults,
never replace them.

**Important:** the scripts never print the actual secret value. Only
the file path is reported so the audit log itself doesn't become a
leak vector.

---

## Red-team safety

The automated red-team runner (\`red-team-run.sh\`) has multiple safety
layers to prevent accidental use against production:

1. **Hardcoded prod check** -- refuses any URL containing \`prod\` or
   \`production\` (word-boundary regex)
2. **Config blocklist** -- reads \`red_team.never_run_against\` from
   your config and blocks any URL matching those entries
3. **Rate limiting** -- capped at \`red_team.max_rps\` (default 10
   requests/second)
4. **Red-team header** -- every request includes
   \`X-Red-Team: tekimax-security\` so staging logs can identify test traffic
5. **Staging URL required** -- the runner refuses to start without an
   explicit staging URL in config or environment

---

## Chat Worker security

The docs chat at [speckit.tekimax.com/chat](https://speckit.tekimax.com/chat)
runs on Cloudflare Workers with these defenses:

| Defense | Implementation |
|---------|---------------|
| CORS origin allowlist | Only \`ALLOWED_ORIGIN\` (production domain); localhost requires explicit \`ALLOW_LOCAL_ORIGINS=true\` |
| Input validation | Max 20 messages, 4000 chars per message, 20000 chars total |
| Rate limiting | Cloudflare native binding: 20 req / 60s per client IP |
| Response size cap | 64 KiB TransformStream backstop |
| No API keys in code | Workers AI binding (Cloudflare authenticates internally) |
| Grounded answers | System prompt instructs model to answer only from the docs corpus |

---

## What speckit-security is NOT

This extension is **one layer** of a broader security program:

- It is **not** a SAST tool -- it catches spec-level and commit-level issues,
  not runtime vulnerabilities in your application code
- It is **not** a dependency scanner -- use \`npm audit\`, Snyk, or
  Dependabot alongside it
- It is **not** a WAF or runtime monitor -- it enforces that guardrails
  *exist*, not that they *work* at runtime
- It is **not** a penetration testing replacement -- the red-team runner
  tests AI-specific attack surfaces (prompt injection, jailbreak,
  extraction), not network or infrastructure vulnerabilities

Use it alongside your existing security tooling. It plugs the gap
between "we wrote a spec" and "we verified the spec's security
controls exist before writing code."

## ARTICLES

=== ARTICLE PAGE: "Launching speckit-security: the security layer Spec Kit didn't ship with" ===
URL: /articles/blog/launching-speckit-security
Description: "Why we built a security-first extension for GitHub Spec Kit, how we use it on real projects, and what we found when we ran it on our own codebase."
## The gap

[GitHub Spec Kit](https://github.com/github/spec-kit) is a genuinely
good tool. It packages templates, prompts, and slash commands into a
structured workflow that moves an AI coding agent from "specify this
feature" through "plan it", "break it into tasks", and "implement it"
without the usual vibe-coding chaos. Eighty-five thousand stars. An
active community. A well-designed extension API. It works.

What it does **not** do is enforce any security discipline.

There's no built-in threat model step. No data contract validation.
No check that an AI feature has a pinned model version and a rollback
plan. No scan for inline system prompts committed to source. No red
team workflow. None of it.

That's not a criticism of Spec Kit — it's deliberately the
spec-driven development *framework*, not the security framework.
But for teams shipping AI products to regulated buyers, the absence
is a gap that compounds into incidents later. You move fast through
\`/speckit.specify\` and \`/speckit.implement\`, ship a feature, and a
month later an LLM leaks PII through a prompt a reviewer never saw,
or a model version silently drifts from "gemini-2.5" to "latest" and
breaks your evals in production.

We saw that pattern enough times to stop hoping someone else would
fix it, and we built \`speckit-security\`.

## What it is

\`speckit-security\` is a Spec Kit extension. Not a fork, not a
replacement, not a parallel CLI — it installs via
\`specify extension add\` and it plugs into Spec Kit's existing hook
system. Every command it adds is an ordinary
\`/speckit.tekimax-security.*\` slash command that your AI agent
(Claude Code, Copilot, Cursor, Gemini, OpenCode, Windsurf, and 15+
others) picks up automatically.

It adds **six security gates** to the SDD lifecycle:

1. **Data Contract** — before DESIGN, the spec must declare sources,
   schemas (Zod), PII strategy, bias audit, drift thresholds, and
   retention policy. A real Zod file has to exist, and it can't use
   \`z.any()\`.
2. **Threat Model** — STRIDE coverage for every entry point, with no
   High/Critical threats marked \`[UNMITIGATED]\` at DESIGN time.
3. **Model Governance** — for AI features, the model version must be
   pinned (no \`"latest"\`, no \`"stable"\`), and the rollback plan must
   be documented.
4. **Guardrails** — a versioned guardrail YAML with input
   \`blocked_patterns\` and output \`redact_patterns\` has to exist
   before implement.
5. **Red Team** — before ship, a red team report file must exist. An
   automated runner can execute the scenarios against a staging
   endpoint with safety guards (it refuses any URL containing \`prod\`
   or \`production\`, and rate-limits itself).
6. **Inline Content Scan** — blocks inline system prompts in \`src/\`,
   committed secrets anywhere in the repo, and \`.env\` files tracked
   by git.

Each gate is a real POSIX bash script with no package-manager
dependencies (just \`bash\` and \`python3\`, which every macOS and Linux
system already ships). The scripts complete in under a second,
and they append append-only JSONL entries to a gate log per feature
so you get an audit trail for free.

Five **phase hooks** wire the gates into Spec Kit's lifecycle so
they fire automatically:

- \`after_specify\` → data contract
- \`after_plan\` → threat model
- \`before_implement\` → gate check (blocks on failure)
- \`after_implement\` → post-implementation audit
- \`before_analyze\` → red team

Plus eight slash commands, an install-rules command that writes our
engineering discipline into the spec-kit constitution and your
agent's context file so the AI inherits the rules automatically,
and a generic rules template any project can adopt.

All of it is Apache-2.0. All of it is on GitHub. All of it works
with the stock Spec Kit install — no fork required.

## How we use it

TEKIMAX ships AI features to clients who care about compliance. The
hard part of that work isn't writing the AI code — most AI features
are a few hundred lines of prompt engineering and glue. The hard
part is the discipline around those few hundred lines: Are the
schemas actually enforced at runtime? Is the model version pinned?
Is there a rollback? Is there a threat model? Has anyone run a
prompt-injection test against it?

We use \`speckit-security\` as the enforcement layer on every client
feature that touches AI. The workflow is the same every time:

1. \`/speckit.specify\` — outline the feature
2. The \`after_specify\` hook auto-fires and writes the data contract
   section into the spec (schemas, PII, bias, drift, retention)
3. \`/speckit.plan\` — Spec Kit generates the implementation plan
4. The \`after_plan\` hook auto-fires and runs a STRIDE threat model
   against the plan
5. \`/speckit.tekimax-security.guardrails\` and \`model-governance\` to
   wire the AI-specific sections
6. \`/speckit.tasks\` — Spec Kit breaks down the work
7. The \`before_implement\` hook runs the full gate check. **If any
   gate fails, implementation is blocked.** This is the whole point:
   the developer can't accidentally skip the discipline, because the
   tool refuses to proceed.
8. \`/speckit.implement\` — Spec Kit writes the code
9. The \`after_implement\` hook runs the audit, which scans for inline
   prompts, committed secrets, and direct model SDK imports outside
   the feature's designated gateway file
10. \`/speckit.tekimax-security.red-team\` generates adversarial
    scenarios and (optionally) runs them against staging
11. \`/speckit.analyze\` — Spec Kit's final pre-ship analysis

The developer writes the spec, reviews the generated sections, fixes
whatever the gates flag, and ships. The discipline is inherited by
default, not imposed by memory.

## How we found the bugs in our own tool

The most useful thing that happened this week is that we ran
\`speckit-security\` on the documentation site for \`speckit-security\`.

The docs site is a Next.js + Fumadocs project. It has a
\`customization.md\` page that explains, in words, how the audit
script detects secret patterns. So the page contains literal
strings like \`sk_live_\` and \`PRIVATE_KEY\` and \`BEGIN RSA\` — as
*documentation of what to detect*.

Next.js bundles every MDX page into compiled JavaScript in
\`.next/server/chunks/*.js\`. When we ran the audit against the docs
project, it walked the filesystem looking for secret patterns and
hit every compiled chunk of the page that documents the secret
patterns. Eight critical findings on our own documentation
describing the audit.

Two bugs at once:

1. The exclusion list didn't include \`.next/\`, \`out/\`, \`.source/\`,
   or \`.wrangler/\`. Build-output directories are always gitignored,
   but the audit was walking the filesystem, not the git index.
2. The pattern matchers were too loose. \`sk_live_\` alone was
   enough — no trailing key material required. So any string that
   mentioned the prefix, anywhere, would match.

Neither bug was hypothetical. Both would have burned every single
user the moment they ran the audit against a real framework-based
project. And neither bug had shown up in our test suite, because
the tests all used isolated fixtures — they never audited a real
project with real build output and real documentation.

We fixed both in the same release (\`v0.2.3\`) and added two
regression tests that encode each failure mode as a scenario.
The fix to the regex required a subtle trick: the test has to
contain real-looking key material to prove the regex still catches
real keys, but the literal can't appear in the source file or
GitHub's push protection scanner blocks the commit. We solved it by
assembling the string at runtime via \`printf\`, the same pattern
already used by an earlier test for the same reason.

**This is dogfooding doing its job.** We found a class of bug that
no unit test would have caught, because the bug only shows up when
the tool is run against a real project with real build artifacts
and real documentation.

## What's next

The open source extension is at \`v0.2.3\` and the CI pipeline
automatically builds, tests on both Ubuntu and macOS, and deploys
this documentation site to Cloudflare Pages on every push. The test
suite is at 10 tests and growing incrementally — every bug fix
lands with a regression test.

The near-term roadmap is straightforward:

- More agent coverage — we've hands-on verified Claude Code,
  OpenCode, Copilot, Gemini CLI, and Cursor. The other 15+ agents
  Spec Kit supports should work (the translation happens in Spec
  Kit, not in our code) but we haven't tested each one.
- A plugin system for teams that want to register custom gates or
  audit checks. The shape is in planning — not shipped yet because
  we'd rather design it around real use cases than speculate.
- Public catalog submission to the Spec Kit community extensions
  registry (the PR is already open, waiting on maintainer review).

One more note: we also maintain an **extended version** of
\`speckit-security\` that we use internally for client deployments
where the compliance and runtime hardening requirements go beyond
what belongs in an open source project. That version adds things
like signed audit attestation, runtime middleware generators for
features we configure per-customer, and deeper compliance preflights
for SOC 2 and similar regimes. It's not public and it's not part of
what's documented here — but if you're a team shipping AI products
that need that level of rigor and you'd rather not build it
yourself, reach out to **support@tekimax.com**.

## Try it

The open-source extension is genuinely useful by itself. If you're
using Spec Kit, or you're about to use Spec Kit, install
\`speckit-security\` as the security layer:

\`\`\`bash
# Install Spec Kit (one time per machine)
uv tool install specify-cli --from git+https://github.com/github/spec-kit.git

# Clone and install the extension
git clone https://github.com/TEKIMAX/speckit-security
cd /path/to/your-spec-kit-project
specify extension add --dev /path/to/speckit-security
\`\`\`

See the [Getting Started](/docs/getting-started) guide for the
10-minute walkthrough and [How It Works](/docs/how-it-works) for
the detailed per-gate breakdown.

Feedback, bug reports, and pull requests welcome at the
[GitHub repo](https://github.com/TEKIMAX/speckit-security). Security
reports: **security@tekimax.com**. Everything else:
**support@tekimax.com**.

— Christian Kaman, TEKIMAX

---

=== ARTICLE PAGE: "v0.2.3 — audit precision fixes" ===
URL: /articles/news/v0-2-3-released
Description: "Tightens the secret detection regex and excludes build-artifact directories. Two regression tests added. Found by running the audit against our own docs."
## What's fixed

Two classes of false positive in \`audit.sh\` and \`gate-check.sh\` Gate
F, both found by running the audit against this documentation site.

**1. Build-artifact walking.** The scripts walked the filesystem for
secret patterns and hit compiled output under \`.next/\`, \`out/\`,
\`.source/\`, and \`.wrangler/\`. Those directories are gitignored but
the scripts weren't excluding them. All four are now in the
exclusion regex alongside \`node_modules/\`, \`.git/\`, and \`dist/\`.

**2. Pattern over-matching.** The regexes matched bare prefixes like
\`sk_live_\` and the bare identifier \`PRIVATE_KEY\`. Any documentation
that *mentions* these patterns — including our own customization
page — tripped the audit. The patterns are now tight:

- \`sk_live_[0-9a-zA-Z]{24,}\` (Stripe live keys are 24+ chars)
- \`sk_test_[0-9a-zA-Z]{24,}\`
- Full PEM header \`-----BEGIN (RSA |EC |DSA |OPENSSH |ENCRYPTED )?PRIVATE KEY-----\`
- \`xoxb-[0-9a-zA-Z-]{20,}\` for Slack bot tokens
- \`ghp_\`, \`gho_\`, \`ghs_\` + 36 chars for GitHub tokens

AWS \`AKIA[0-9A-Z]{16}\` and Google \`AIza[0-9A-Za-z_-]{35}\` were
already tight and unchanged.

## Regression tests

Two new tests encode both failure modes:

- \`tests/audit/skip-build-artifacts.sh\` plants real-looking key
  material inside \`.next/\` and \`out/\` and asserts the audit still
  passes clean. Test payloads are assembled at runtime via \`printf\`
  so the literal tokens never appear in committed source (avoids
  tripping GitHub's push protection on the test file itself).
- \`tests/audit/skip-doc-mentions.sh\` plants bare doc-style prefix
  mentions in a \`src/\` file and asserts the audit passes clean.

The test suite is now **10 tests, all passing** on macOS bash 3.2
and Ubuntu latest.

## Upgrade

\`\`\`bash
cd /path/to/your-speckit-security-clone
git pull
# then reinstall into any affected projects
cd /path/to/project
specify extension remove tekimax-security
specify extension add --dev /path/to/speckit-security
\`\`\`

Or on the [releases page](https://github.com/TEKIMAX/speckit-security/releases/tag/v0.2.3).

The full story of how we found the bugs is in the blog post
["Launching speckit-security"](/articles/blog/launching-speckit-security) —
the short version is: we audited our own documentation site and the
audit flagged itself.`;

export const DOCS_CONTEXT_BYTES = 80824;
